import type { Icon } from '@phosphor-icons/react'
import {
  GlobeIcon,
  FileTextIcon,
  ListIcon,
  FlagBannerIcon,
  RowsIcon,
  SquaresFourIcon,
  CardsIcon,
  ClipboardTextIcon,
  PictureInPictureIcon,
  SquareHalfBottomIcon,
  TextTIcon,
  ImageIcon,
  CursorClickIcon,
  SquareIcon,
  PuzzlePieceIcon,
  LockIcon,
  PaletteIcon,
  TextAaIcon,
  SparkleIcon,
  ArrowsOutIcon,
  PushPinIcon,
  LightningIcon,
  GearIcon,
  DiceFiveIcon,
  PencilSimpleLineIcon,
  ImageSquareIcon,
  SpeakerHighIcon,
  VideoCameraIcon,
  ChatCircleDotsIcon,
  LightbulbIcon,
  FlagIcon,
  ClockCounterClockwiseIcon,
  PlusIcon,
  CakeIcon,
  DownloadSimpleIcon,
  ArrowCounterClockwiseIcon,
  ArrowClockwiseIcon,
  QuestionIcon,
  MinusIcon,
  EqualsIcon,
  CaretDownIcon,
  CheckIcon,
  XIcon,
} from '@phosphor-icons/react'

export const ICONS = {
  site: GlobeIcon,
  page: FileTextIcon,
  navbar: ListIcon,
  hero: FlagBannerIcon,
  section: RowsIcon,
  cardgrid: SquaresFourIcon,
  card: CardsIcon,
  form: ClipboardTextIcon,
  popup: PictureInPictureIcon,
  footer: SquareHalfBottomIcon,
  text: TextTIcon,
  image: ImageIcon,
  button: CursorClickIcon,
  box: SquareIcon,
  custom: PuzzlePieceIcon,
  checkpoint: LockIcon,
  t_color: PaletteIcon,
  t_font: TextAaIcon,
  t_vibe: SparkleIcon,
  t_size: ArrowsOutIcon,
  t_position: PushPinIcon,
  t_onclick: LightningIcon,
  t_purpose: GearIcon,
  t_fakedata: DiceFiveIcon,
  t_text: PencilSimpleLineIcon,
  t_image: ImageSquareIcon,
  t_sound: SpeakerHighIcon,
  t_video: VideoCameraIcon,
  t_tellbob: ChatCircleDotsIcon,
  t_bobpicks: LightbulbIcon,
  flag: FlagIcon,
  tab_canvas: PuzzlePieceIcon,
  tab_library: ImageIcon,
  tab_checkpoints: ClockCounterClockwiseIcon,
  new: PlusIcon,
  demo: CakeIcon,
  download: DownloadSimpleIcon,
  undo: ArrowCounterClockwiseIcon,
  redo: ArrowClockwiseIcon,
  help: QuestionIcon,
  zoom_in: PlusIcon,
  zoom_out: MinusIcon,
  zoom_reset: EqualsIcon,
  fold: CaretDownIcon,
  check: CheckIcon,
  close: XIcon,
  reload: ArrowClockwiseIcon,
} satisfies Record<string, Icon>

export type IconKey = keyof typeof ICONS
